name: dash_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - dash
  - dash-core-components
  - dash-html-components
  - dash-renderer
  - dash-table
  - plotly
  - pandas
  - numpy
  - scipy
  - gunicorn # For deployment
  - pip
  - pip:
    - flask-caching