name: dash_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.19
  - dash=2.16.1
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-renderer=1.9.1
  - dash-table=5.0.0
  - plotly=5.19.0
  - pandas=2.0.3
  - numpy=1.24.4
  - scipy=1.10.1
  - gunicorn=21.2.0 # For deployment
  - joblib=1.3.2
  - pip=24.0
  - pip:
    - flask-caching==2.1.0
    - scikit-learn==1.3.2
    - dash-bootstrap-components==1.5.0